import { describe, expect, it } from 'vitest';
import { normalizeGstin, validateGstin } from '../src/gstin';
import { calculateGst, classifySupply } from '../src/tax';
import { calculateInvoice, calculateLineItem } from '../src/invoice';
import { buildHsnSummary, toUqc, validateHsn, validateSac } from '../src/hsn';
import { buildGstr1 } from '../src/gstr1';
import { buildGstr3b } from '../src/gstr3b';

describe('GSTIN',()=>{it('normalizes and structurally validates',()=>{expect(normalizeGstin(' 27aapfu0939f1zv ')).toBe('27AAPFU0939F1ZV');expect(validateGstin('27AAPFU0939F1ZV')).toMatchObject({valid:true,stateCode:'27',stateName:'Maharashtra'});});it('rejects bad format/state',()=>expect(validateGstin('00ABCDE1234F1Z5').valid).toBe(false));});
describe('tax',()=>{it('splits intra-state tax without losing paise',()=>expect(calculateGst({taxableValue:999.99,rate:18,supplyType:'intraState'})).toMatchObject({cgstAmount:90,sgstAmount:90,igstAmount:0,totalTax:180}));it('uses IGST inter-state',()=>{const type=classifySupply({supplierState:'27',placeOfSupply:'29'});expect(type).toBe('interState');expect(calculateGst({taxableValue:1000,rate:18,supplyType:type})).toMatchObject({igstAmount:180,cgstAmount:0,sgstAmount:0});});it('names nearest-rupee strategy',()=>expect(calculateGst({taxableValue:99.5,rate:18,supplyType:'interState',rounding:'nearestRupee'}).igstAmount).toBe(18));});
describe('invoice',()=>{it('calculates cascading discounts, free goods and round off',()=>{const line=calculateLineItem({quantity:2,freeQuantity:1,unitPrice:100,discountPercent:10,discount2Percent:10,gstRate:18},{supplierState:'27',placeOfSupply:'27'});expect(line).toMatchObject({grossAmount:200,discountAmount:38,taxableValue:162,cgstAmount:14.58,sgstAmount:14.58,freeGoodsValue:100});expect(calculateInvoice([line])).toMatchObject({totalAmount:191,roundOff:-0.16,shippedQuantity:3});});});
describe('HSN/SAC',()=>{it('validates formats and aggregates',()=>{expect(validateHsn('84713010')).toBe(true);expect(validateSac('998314')).toBe(true);expect(toUqc('kg')).toBe('KGS-KILOGRAMS');expect(buildHsnSummary([{hsnSac:'8471',unit:'PCS',quantity:2,taxableValue:1000,gstRate:18,cgstAmount:90,sgstAmount:90}])[0]).toMatchObject({totalQuantity:2,totalTax:180});});});
describe('returns',()=>{it('builds GSTR-1 B2B output',()=>{const result=buildGstr1({gstin:'27AAPFU0939F1ZV',fp:'042026',invoices:[{inum:'INV-1',idt:'2026-04-10',customerGstin:'29ABCDE1234F1Z5',placeOfSupply:'29',lines:[{hsn:'8471',qty:1,rt:18,txval:1000}]}]});expect(result.issues.filter(x=>x.level==='error')).toHaveLength(0);expect(result.json.b2b?.[0]?.inv[0]?.inum).toBe('INV-1');});it('builds GSTR-3B output with defaults',()=>{const zero={txval:0,iamt:0,camt:0,samt:0,csamt:0};const result=buildGstr3b({gstin:'27AAPFU0939F1ZV',ret_period:'042026',sup_details:{osup_det:{...zero,txval:1000,iamt:180},osup_zero:{txval:0,iamt:0,csamt:0},osup_nil_exmp:{txval:0},isup_rev:zero,osup_nongst:{txval:0}}});expect(result.issues).toHaveLength(0);expect(result.json.sup_details.osup_det.iamt).toBe(180);expect(result.json.itc_elg?.itc_avl).toHaveLength(5);});});
