import { calculateGst, classifySupply, roundMoney, roundToRupee, type RoundingStrategy, type SupplyContext } from '../tax/index';
export interface InvoiceLineInput { id?:string; description?:string; hsnSac?:string; quantity:number; freeQuantity?:number; unitPrice:number; discountPercent?:number; discount2Percent?:number; gstRate:number; cessRate?:number; }
export interface CalculatedInvoiceLine extends InvoiceLineInput { grossAmount:number; discountAmount:number; taxableValue:number; cgstAmount:number; sgstAmount:number; igstAmount:number; cessAmount:number; totalAmount:number; freeGoodsValue:number; }
export function calculateLineItem(line:InvoiceLineInput,context:SupplyContext,rounding:RoundingStrategy='money2'):CalculatedInvoiceLine {
 const grossAmount=roundMoney(line.quantity*line.unitPrice); const d1=roundMoney(grossAmount*(line.discountPercent??0)/100); const d2=roundMoney((grossAmount-d1)*(line.discount2Percent??0)/100); const discountAmount=roundMoney(d1+d2); const taxableValue=roundMoney(Math.max(0,grossAmount-discountAmount)); const tax=calculateGst({taxableValue,rate:line.gstRate,cessRate:line.cessRate,supplyType:classifySupply(context),rounding});
 return {...line,grossAmount,discountAmount,taxableValue,cgstAmount:tax.cgstAmount,sgstAmount:tax.sgstAmount,igstAmount:tax.igstAmount,cessAmount:tax.cessAmount,totalAmount:roundMoney(taxableValue+tax.totalTax),freeGoodsValue:roundMoney((line.freeQuantity??0)*line.unitPrice)};
}
export interface InvoiceTotals { subtotal:number; lineDiscounts:number; invoiceDiscount:number; taxableValue:number; cgstAmount:number; sgstAmount:number; igstAmount:number; cessAmount:number; roundOff:number; totalAmount:number; billedQuantity:number; shippedQuantity:number; freeGoodsValue:number; }
export function calculateInvoice(lines:CalculatedInvoiceLine[],options:{invoiceDiscountPercent?:number;roundOff?:boolean}={}):InvoiceTotals {
 const sum=(key:keyof CalculatedInvoiceLine)=>lines.reduce((n,l)=>n+Number(l[key]??0),0); const subtotal=sum('grossAmount'); const lineDiscounts=sum('discountAmount'); const taxableBefore=sum('taxableValue'); const invoiceDiscount=roundMoney(subtotal*(options.invoiceDiscountPercent??0)/100); const taxableValue=roundMoney(Math.max(0,taxableBefore-invoiceDiscount)); const scale=taxableBefore>0?taxableValue/taxableBefore:1; const adj=(key:keyof CalculatedInvoiceLine)=>roundMoney(sum(key)*scale); const cgstAmount=adj('cgstAmount'),sgstAmount=adj('sgstAmount'),igstAmount=adj('igstAmount'),cessAmount=adj('cessAmount'); const before=taxableValue+cgstAmount+sgstAmount+igstAmount+cessAmount; const roundOff=options.roundOff===false?0:roundMoney(roundToRupee(before)-before); return {subtotal:roundMoney(subtotal),lineDiscounts:roundMoney(lineDiscounts),invoiceDiscount,taxableValue,cgstAmount,sgstAmount,igstAmount,cessAmount,roundOff,totalAmount:roundMoney(before+roundOff),billedQuantity:roundMoney(sum('quantity'),3),shippedQuantity:roundMoney(lines.reduce((n,l)=>n+l.quantity+(l.freeQuantity??0),0),3),freeGoodsValue:roundMoney(sum('freeGoodsValue'))};
}
